const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path'),fs=require('node:fs');
const baseURL=process.env.MODEL_URL||'http://127.0.0.1:8000/index.html';
const artifactDir=process.env.ARTIFACT_DIR;
if(artifactDir)fs.mkdirSync(artifactDir,{recursive:true});
let browser;
(async()=>{
browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const check=async(name,expression)=>{assert(await page.evaluate(expression),name);console.log('PASS',name)};
const snapshot=async name=>{if(artifactDir)await page.screenshot({path:path.join(artifactDir,name+'.png'),timeout:60000})};
const settle=()=>page.waitForFunction(()=>Math.abs(th-thT)<.02&&Math.abs(ph-phT)<.02&&Math.abs(r-rT)<.05&&cameraTarget.distanceTo(tg)<.08&&Math.abs(sep-sepT)<.005&&Math.abs(xr-xrT)<.005,{},{timeout:45000});
await page.goto(baseURL+'#relay');await settle();
await check('relay defaults to enclosure',()=>activeNode==='relay'&&relayFraming==='box'&&Math.abs(cameraTarget.y+9)<.1&&activeParts.length===10);
await check('coax external plus internal route fits 3 metres',()=>{
 const outer=coax.children[0].geometry.parameters.path.getLength();
 const internal=relayLeads.find(l=>l.a===relayRadio&&l.b===relayBoxPart).mesh.geometry.parameters.path.getLength();
 return (outer+internal)/7<=3;
});
await page.getByRole('button',{name:'Antenna',exact:true}).click();await settle();
await check('antenna focus centers elevated antenna',()=>relayFraming==='antenna'&&Math.abs(cameraTarget.y-17.2)<.15);
await snapshot('kalasag-antenna');
await page.getByRole('button',{name:'Full tower',exact:true}).click();await settle();
await check('full tower is framed in desktop canvas',()=>{cam.updateMatrixWorld();const b=new T.Box3().setFromObject(tower).union(new T.Box3().setFromObject(antenna));for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const v=new T.Vector3(x,y,z).project(cam);const rect=stage.getBoundingClientRect(),py=rect.top+(-v.y*.5+.5)*rect.height;if(Math.abs(v.x)>1||py<$('#inspection-nav').getBoundingClientRect().bottom||py>$('#ctl').getBoundingClientRect().top)return false}return true});
await page.getByRole('button',{name:'Enclosure',exact:true}).click();await settle();
const canvas=await page.locator('#cv').boundingBox(),x=canvas.x+canvas.width*.7,y=canvas.y+canvas.height*.5;
await page.mouse.move(x,y);await page.mouse.wheel(0,-150);await page.waitForTimeout(500);const radius=await page.evaluate(()=>rT);
await page.keyboard.down('Shift');await page.mouse.down();await page.mouse.move(x,y-90,{steps:5});await page.mouse.up();await page.keyboard.up('Shift');
await check('shift drag raises focus while retaining zoom',()=>panYT>0&&rT<nodeRegistry.relay.baseR);assert.equal(await page.evaluate(()=>rT),radius);
await page.getByRole('button',{name:'Reset view',exact:true}).click();await settle();await check('reset returns to enclosure and canonical orbit',()=>relayFraming==='box'&&panYT===0&&thT===.38&&phT===1.35);
await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+60,y+10,{steps:5});await page.mouse.up();await check('mouse orbit',()=>thT!==.38);
await page.getByRole('tab',{name:'Console Node',exact:true}).click();await settle();
await check('console has seven selectable 3D components',()=>activeParts===consoleParts&&consoleParts.length===7&&activePick.length>100&&!stage.classList.contains('console-mode'));
for(let i=0;i<7;i++){await page.locator('#list button').nth(i).click();await check('console selection '+(i+1),()=>sel&&info.querySelector('h2').textContent===sel.name)}
assert(await page.locator('#ctl').isVisible(),'Hardware inspection controls remain visible');
await page.getByRole('button',{name:'X-ray',exact:true}).click();await settle();await check('console X-ray exposes case',()=>consoleLid.children[0].material.opacity<.15);
await snapshot('kalasag-console-xray');
await page.getByRole('button',{name:'Exploded',exact:true}).click();await settle();await check('console exploded offsets and attached wire endpoints',()=>{if(consoleLid.position.z<5.8||cpEsp.obj.position.z<2.9)return false;consoleRoot.updateMatrixWorld(true);return consoleLeads.every(l=>{const p=new T.Vector3().fromBufferAttribute(l.mesh.geometry.attributes.position,0);consoleHarness.localToWorld(p);const end=l.a.obj.localToWorld(new T.Vector3(...l.ap));return p.distanceTo(end)<.06})});
await snapshot('kalasag-console-exploded');
await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByRole('button',{name:'Send test alert'}).click();await page.waitForTimeout(4000);
await check('test incident metadata and automatic acknowledgement',()=>flowState===3&&!dispatchHelp.disabled&&$('#incident-spatial').textContent.includes('304')&&$('#incident-ack').textContent.includes('Acknowledged')&&$('#incident-received').textContent!=='—');
await snapshot('kalasag-dashboard');
await page.getByRole('button',{name:'Dispatch response'}).click();await check('dispatch final state',()=>flowState===4&&dispatchHelp.disabled&&$('#incident-count').textContent==='0'&&$('#incident-dispatch').textContent.startsWith('Dispatched'));
await page.getByRole('button',{name:'Send test alert'}).click();await page.waitForTimeout(850);await page.getByRole('button',{name:'Acknowledge',exact:true}).click();await page.getByRole('button',{name:'Dispatch response'}).click();await page.waitForTimeout(800);await check('auto acknowledgement cannot regress operator dispatch',()=>flowState===4&&dispatchHelp.disabled);
await page.getByRole('button',{name:'Send test alert'}).click();await page.getByRole('button',{name:'Reset',exact:true}).click();await page.waitForTimeout(1600);await check('reset cancels pending timers',()=>flowState===0&&$('#incident-spatial').textContent==='—'&&dispatchHelp.disabled&&ackAlert.disabled);
await page.setViewportSize({width:390,height:844});await page.getByRole('tab',{name:'Relay Tower',exact:true}).click();await settle();
await page.getByRole('button',{name:'Full tower',exact:true}).click();await settle();await check('full tower fits mobile viewport',()=>{cam.updateMatrixWorld();const b=new T.Box3().setFromObject(tower).union(new T.Box3().setFromObject(antenna));for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const v=new T.Vector3(x,y,z).project(cam);const rect=stage.getBoundingClientRect(),py=rect.top+(-v.y*.5+.5)*rect.height;if(Math.abs(v.x)>1||py<$('#inspection-nav').getBoundingClientRect().bottom||py>$('#ctl').getBoundingClientRect().top)return false}return true});
await snapshot('kalasag-relay-mobile');
const cdp=await page.context().newCDPSession(page);const rect=await page.locator('#cv').boundingBox();const ty=rect.y+rect.height*.6;
await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:120,y:ty,id:1},{x:240,y:ty,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:100,y:ty-40,id:1},{x:260,y:ty-40,id:2}]});
await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
await check('two-finger pan and pinch on mobile',()=>panYT>0&&rT<nodeRegistry.relay.baseR&&pts.size===0);
await page.locator('#mast-height').fill('4');await page.locator('#mast-height').dispatchEvent('input');await check('height slider reaches mast top',()=>Math.abs(focusTargets[relayFraming].y+panYT-14)<.01);
const saved=await page.evaluate(()=>({focus:relayFraming,pan:panYT,r:rT}));await page.getByRole('tab',{name:'Console Node',exact:true}).click();await page.getByRole('tab',{name:'Relay Tower',exact:true}).click();const restored=await page.evaluate(()=>({focus:relayFraming,pan:panYT,r:rT}));assert.equal(restored.focus,saved.focus);assert.equal(restored.pan,saved.pan);assert(Math.abs(restored.r-saved.r)<1e-8);console.log('PASS relay navigation persists across tabs');
await page.getByRole('button',{name:'Reset view',exact:true}).click();await settle();await page.getByRole('button',{name:'X-ray',exact:true}).click();await settle();
await check('relay dynamic wiring is preserved',()=>relayLeads.length>10&&relayLeads.every(l=>{const v=new T.Vector3().fromBufferAttribute(l.mesh.geometry.attributes.position,0);relayHarness.localToWorld(v);return v.distanceTo(l.a.obj.localToWorld(new T.Vector3(...l.ap)))<.05}));
await page.getByRole('tab',{name:'Console Node',exact:true}).click();await page.getByRole('button',{name:'Hardware',exact:true}).click();await page.getByRole('button',{name:'Exploded',exact:true}).click();await settle();await snapshot('kalasag-console-mobile-exploded');
await page.getByRole('button',{name:'Dashboard',exact:true}).click();assert(!(await page.locator('aside').isVisible()),'Dashboard uses the full workspace');await page.getByRole('button',{name:'Hardware',exact:true}).click();await page.locator('#list button').nth(1).click();await check('dashboard hardware selection opens the 3D view',()=>consoleView==='hardware'&&sel===cpEsp);await page.getByRole('button',{name:'Dashboard',exact:true}).click();await page.getByRole('button',{name:'Send test alert'}).click();await page.waitForTimeout(1700);await snapshot('kalasag-dashboard-mobile');
await page.getByRole('tab',{name:'Distress Node',exact:true}).click();await settle();await check('distress BOM components and removed additions',()=>{
 const names=parts.map(p=>p.name);
 return ['ADXL345 GY-291 accelerometer','TP5000 LiFePO4 charger','5 V wall adapter','1/4 W 1% resistors','Electrolytic supply capacitors','DS3231 RTC module'].every(n=>names.includes(n))&&
 ['SW-420 vibration sensor','LiFePO4 power-path charger','MCP23017 I/O expander','3.3 V buck-boost regulator','3.3 V power distribution','Clear hinged button cover'].every(n=>!names.includes(n))&&wall.visible&&root.visible&&!relayRoot.visible&&!consoleRoot.visible;
});
await check('all components link to sheet authority',()=>[...parts,...relayParts,...consoleParts].every(p=>p.source.links.some(l=>l[1]===componentSheet)));
await check('three full-size backup cells are displayed',()=>{const p=byName('IFR18650 LiFePO4 backup cells');let cells=0;p.obj.traverse(o=>{if(o.isMesh&&o.geometry.type==='CylinderGeometry'&&o.geometry.parameters.height===6.5)cells++});return cells===3&&p.spec.includes('does not specify pack quantity')});
const legend=await page.locator('#light-legend').innerHTML();
await page.waitForTimeout(4500);
assert.equal(await page.locator('#light-legend').innerHTML(),legend);
await check('legend labels remain visible and RGB LED stays unlit',()=>!$('#light-legend').hidden&&$('#light-legend').children.length===5&&rgb.m.emissiveIntensity===0&&rgb.m.color.getHex()===0xc6d2d8);
await check('only blinking legend states animate',()=>[...document.querySelectorAll('#light-legend i')].every((dot,i)=>getComputedStyle(dot).animationName===(i<2?'legend-blink':'none')));
await page.emulateMedia({reducedMotion:'reduce'});
await check('legend respects reduced motion',()=>[...document.querySelectorAll('#light-legend i')].every(dot=>getComputedStyle(dot).animationName==='none'&&getComputedStyle(dot,'::after').animationName==='none'));
await page.emulateMedia({reducedMotion:'no-preference'});
await check('all three RTC boards include EEPROM geometry',()=>[nodeRtc,relayRtc.obj,cpRtc.obj].every(g=>{let count=0;g.traverse(o=>{if(o.isMesh&&o.material.map)count++});return count>=6}));
await page.getByRole('button',{name:'Exploded',exact:true}).click();await settle();
await check('distress exploded wires remain attached to existing components',()=>leads.every(l=>{
 if(!parts.includes(l.a)||!parts.includes(l.b))return false;
 const v=new T.Vector3().fromBufferAttribute(l.mesh.geometry.attributes.position,0);wiring.localToWorld(v);return v.distanceTo(attachPoint(l.a,l.ap))<.06;
}));
await snapshot('kalasag-distress-bom-exploded');
await page.getByRole('button',{name:'X-ray',exact:true}).click();await settle();
await check('three cells fit between the mobile legend and controls',()=>{
 cam.updateMatrixWorld();const b=new T.Box3().setFromObject(byName('IFR18650 LiFePO4 backup cells').obj),rect=stage.getBoundingClientRect();
 for(const x of [b.min.x,b.max.x])for(const y of [b.min.y,b.max.y])for(const z of [b.min.z,b.max.z]){const v=new T.Vector3(x,y,z).project(cam),py=rect.top+(-v.y*.5+.5)*rect.height;if(Math.abs(v.x)>1||py<$('.ttl').getBoundingClientRect().bottom||py>$('#ctl').getBoundingClientRect().top)return false}return true;
});
await snapshot('kalasag-distress-bom-xray');
assert.deepEqual(errors,[]);console.log('PASS no browser JavaScript or console errors');await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close()});
